apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjbXhwYTJoaFkyaGxkanBuYUhCZlJISnhRM1p3TUhkQlprVlJTazExUm1wdlIxTm9Na1l4Wm5oTVdVYzJNamhPWjJ0M0NnPT0ifX19
type: kubernetes.io/dockerconfigjson
